name: Package Application
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Package & Release app
    runs-on: ubuntu-latest
    steps:
      - name: Clone codebase
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
    #   - name: Get tag name
    #     id: tag
    #     run: echo "name=$(node ./get-release-name.js ${{ github.run_number }})" >> $GITHUB_ENV
      
      - name: Install project dependencies
        run: yarn install --prefer-offline
      
      - name: Install packager
        run: npm install -g pkg

      - name: Package application
        run: pkg -t 'node18-linux-x64,node18-macos-x64,node18-win-x64' 'src/song-seeker.js' --no-bytecode --public-packages "*" --public --compress Brotli
       
      - name: Install wine
        run: |
          sudo apt-get update && sudo apt-get install -y wine 
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32

      - name: Download rcedit
        run: |
          curl -L -o rcedit-x64.exe https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe

      - name: Set icon for Windows executable
        run: |
          cp 'src/assets/icon.ico' icon.ico
          wine rcedit-x64.exe song-seeker-win.exe --set-icon icon.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: song-seeker
          path: song-seeker*
      
      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            song-seeker*
