name: Package Application
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Package & Release app
    runs-on: ubuntu-latest
    steps:
      - name: Clone codebase
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Get tag name
        id: tag
        run: echo "name=$(node ./get-release-name.js ${{ github.run_number }})" >> $GITHUB_ENV
      
      - name: Install project dependencies
        run: yarn install --prefer-offline
      
      - name: Install packager
        run: npm install -g pkg

      - name: Package application
        run: pkg -t 'node18-linux-x64,node18-macos-x64,node18-win-x64' 'src/song-seeker.js' --no-bytecode --public-packages "*" --public
      
      - name: Release asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            song-seeker*