name: Package Application
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Package & Release app
    runs-on: ubuntu-latest
    steps:
      - name: Clone codebase
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install project dependencies
        run: yarn install --prefer-offline
      
      - name: Install packager
        run: npm install -g pkg

      - name: Package application
        run: pkg -t 'node18-linux-x64,node18-macos-x64,node18-win-x64' 'src/song-seeker.js' --no-bytecode --public-packages "*" --public
       
      - name: Install resedit
        run: npm install -g resedit-cli

      - name: Modify Windows exe
        run: resedit -i song-seeker-win.exe -o song-seeker-win.exe --no-grow --icon 'src/assets/icon.ico'
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: song-seeker
          path: song-seeker*
      
      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            song-seeker*
          generate_release_notes: true

